[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
anteroom = "EbGkJPaMY8XCJCNjkWwk971xzE32X5LBPg5s2g4LDYcW"
buy-in = "8JLhyUt84DQxbvQQz1UwXBPRWwQFHc3YDetxrFZZN67n"
buy-inb = "5uHMpZkSyXmERUusARBzf6ACAam9u3EXYa9EA7VW5t2B"
cash-out = "HnT1pk8zrLfQ36LjhGXVdG3UgcHQXQdFxdAWK26bw5bS"
eat-food = "J7R4J1RnFMGdXgEBqwseTR9ZFruAiT1wMAYYc2Hnxsre"
eat-player = "8Gm1Lz8L4dAEypGyctPVnT7p9Y5NapQKvhLdE9dGQLKA"
exit-game = "5hVB37dXEFmEvtu2TST8iXAxvd8VXq3JQmGGLNprMVyo"
init-anteroom = "DbKbkJC5Dw6RvQUkaM4CH7Z5hTcWGP51t7hZ3Hu42rXp"
init-map = "NrQkd31YsAWX6qyuLgktt4VPG4Q2DY94rBq7fWdRgo7"
init-players = "Ru2cmntBkvmUGcg6E7rrDFYrx6ujf1zVJs7hEDq3uT3"
init-section = "3YdRbDukWkyE2tBPoUhPSJzB1MCE1gKnoNjx5WdEq6aE"
map = "2dZ5DLJhEVFRA5xRnRD779ojsWsf3HMi6YB1zmVDdsYb"
movement = "C9yoUrN6yhiKF1DEWV9QPcwaJRrTCCtMVtbJKipVTrEi"
player = "2ewyq31Atu7yLcYMg51CEa22HmcCSJwM4jjHH8kKVAJw"
players = "DM7jvvNssHqKjKXsSoJjrzAQXp9X8rTCDFskyGAjSXQB"
section = "Dnh8jDMM6HDY1bXHt55Fi2yKfUPiu4TMhAJiotfb4oHq"
spawn-food = "A3LybrLCJfYL2F1wrBVaaK1rUnhzpMoGD6Lp5VTqEFNG"
spawn-player = "QMpMFne3WkDRWEvY8LGKQB6n5ox6dvdhsoB8jZFjjmX"
spawn-playerb = "8ahq6aWuNttiBiFjPAMRqhfyhMb85BefnpdZVUVYesyh"

[programs.localnet]

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs-ecs/components/*", "programs-ecs/systems/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[[test.genesis]]
address = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
program = "tests/fixtures/dlp.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "devnet"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
