[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
anteroom = "6PWyQF9YxtQLCZeYtJhPftVg4qXv2pHGyT5NteJVjacJ"
buy-in = "BTLTqowYeJ2tRTTB8mcbbmAwZBDAJG3MUioGNdsTsX13"
buy-inb = "7xHzX2a5VzBkRayf1uyVPTLmwNwNE2Hh4qS1CbEAjPsJ"
cash-out = "Cj5YjoZTXnkbhBmoMNVhp2QfKkAnLS5bpWNDcJNYfGZ4"
cashout-test = "BbsN5y3HkHw11DnfpmbmvRYH9Tag8XNbE91WikaARjEP"
cashout-testb = "A7MW7nu1Mc2y47aW1F1c8LQb5H51f3MXiKezaFsH3mxt"
cashout-testc = "8x4pQTDyoRe49NLiASjebyasW2shv1pRMCTwngSB5ari"
eat-food = "B1M7AtzCds9MyoibMA3UhhrZMJ46BTJvFadvkCr7J71U"
eat-player = "VZ7h6UCzrrWtCm3xBghYSAVXBvHecc34qnyeyeyjASh"
exit-game = "4PvV5ZSgXpUGbzBpDVmaguzG1gWZw2LKpuevYcPPVPtk"
init-anteroom = "5oEk3USUXwmriWFsH5cKzyfmbetYuWvRQpk4ZTzdqs47"
init-map = "68caW8nVmZnUSunBotTTM5wuYQ3aymEsEHuTnsXgec65"
init-players = "84UTvkLscZVoznsgC4ppfQ3xSjBxod617g1nwTqEiMLM"
init-section = "6vFNtK3uopAUxJ4AhXbsfKyb9JZPkKnPvkFXEpUwNSEc"
map = "73x8SGXgkhk84Yk943eJRAVAW3yGoQz5m1Q2sb2THLsA"
movement = "EhLPnGqecy61peHT7j1WRsEWGqUZ11MZzYR4Xxm5RHRj"
player = "39c3gAHBe74wPgfhP5wBRCdcNHuMBY53awGBBjJUeWSw"
players = "DSjd5Y9zWmfXmnhm9vdzqAR1HvbaTs45ueo15SRsAoUq"
section = "2D7pVfWpF8NAqBFJQ5FHfMLzQR2wRZk8dRUf5SV1Hw5N"
spawn-food = "EKSX8KynuiQCkvAZiyiVuYJcEAb77WBUaSUFkhZUqASk"
spawn-player = "BaTXEmj1rf1Jq5uGHLBVrBihLqTA6gSd2ZddmD4rLdaD"

[programs.localnet]

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs-ecs/components/*", "programs-ecs/systems/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[[test.genesis]]
address = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
program = "tests/fixtures/dlp.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "devnet"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
